### ISSUE TITLE
me puedes explicar que hace el mapings, quiero agregar las funcionalidades de tu video de telescope pero estoy algo perdido, y no entiendo en que contexto y el como se ejecuta eso del mappings

### ISSUE THREAD

**Issue by rodlemus** [adalessa/nvim#1]
no entiendo que hace esta funcion
`local rhs = function()
    R("alpha.telescope")[f](opts.options)
  end
`

**Comment by adalessa** [comment]
esta linea lo que hace es definir la funcion que va a utilizar para el keymap.
si ves despues la utiliza para el 
```lua
  vim.keymap.set(opts.mode, key, rhs, map_options)
```
con esto es afuncion queda asignada al mapping.
en si lo que hace ahi es llamar a la funcion R que ela tengo como global que lo que hace es recargar siempre el el archivo por si lo modifique. 
Busca una funcion con el nombre que le pase para definirlo, eso lo podes ver en el archivo init.lua del mismo directorio y le pasa las opciones. Es una manera de tener la definicion de la funcion en otro lado en telecope y no en cada mapping
